# Ch4 数据类型和结构
## 4.1 基本数据类型
### 4.1.1 整数

In [1]:
a = 10
type(a)

int

In [2]:
a.bit_length()

4

In [3]:
a = 1000000
a.bit_length()

20

In [4]:
googol = 10 ** 100
googol

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000L

In [5]:
googol.bit_length()

333

In [6]:
1 + 4

5

In [7]:
1/4

0

### 4.1.2 浮点数

In [8]:
1.0/4

0.25

In [9]:
type(1./4)

float

In [10]:
b = 0.35
type(b)

float

In [13]:
b + 0.1

0.44999999999999996

In [14]:
c = 0.5
c.as_integer_ratio()

(1, 2)

In [15]:
b.as_integer_ratio()

(3152519739159347L, 9007199254740992L)

In [16]:
import decimal
from decimal import Decimal

In [17]:
decimal.getcontext()

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999999, Emax=999999999, capitals=1, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])

In [18]:
d = Decimal(1) / Decimal(11)
d

Decimal('0.09090909090909090909090909091')

In [19]:
decimal.getcontext().prec = 4
e = Decimal(1) / Decimal(11)
e

Decimal('0.09091')

In [20]:
decimal.getcontext().prec = 50
f = Decimal(1) / Decimal(11)
f

Decimal('0.090909090909090909090909090909090909090909090909091')

In [21]:
g = d + e + f
g

Decimal('0.27272818181818181818181818181909090909090909090909')

### 4.1.3 字符串

In [22]:
t = 'this is a string object'

In [23]:
t.capitalize()

'This is a string object'

In [24]:
t.split()

['this', 'is', 'a', 'string', 'object']

In [25]:
t.find('string')

10

In [26]:
t.find('Python')

-1

In [27]:
t.replace(' ','|')

'this|is|a|string|object'

In [28]:
'http://www.python.org'.strip('htp:/')

'www.python.org'

In [29]:
import re

In [30]:
series = """
'01/18/2014 13:00:00',100,'1st';
'01/18/2014 13:20:00',110,'2nd';
'01/18/2014 14:00:00',120,'3rd'
"""

In [31]:
dt = re.compile("'[0-9/:\s]+'") # datetime

In [32]:
result = dt.findall(series)
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:20:00'", "'01/18/2014 14:00:00'"]

In [33]:
from datetime import datetime
pydt = datetime.strptime(result[0].replace("'",""),
                        '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

In [34]:
print pydt

2014-01-18 13:00:00


In [35]:
print type(pydt)

<type 'datetime.datetime'>


## 4.2 基本数据结构
### 4.2.1 元组

In [36]:
t = (1,2.5,'data')
type(t)

tuple

In [37]:
t = 1,2.5,'data'
type(t)

tuple

In [38]:
t[2]

'data'

In [39]:
type(t[2]) 

str

In [40]:
t.count('data')

1

In [41]:
t.index(1)

0

### 4.2.2 列表

In [42]:
l = [1,2.5,'data']
l[2]

'data'

In [43]:
l = list(t)
l

[1, 2.5, 'data']

In [44]:
type(l)

list

In [45]:
l.append([4,3])
l

[1, 2.5, 'data', [4, 3]]

In [46]:
l.extend([1.0,1.5,2.0])
l

[1, 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [47]:
l.insert(1,'insert')
l

[1, 'insert', 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [48]:
l.remove('data')
l

[1, 'insert', 2.5, [4, 3], 1.0, 1.5, 2.0]

In [49]:
p = l.pop(3)
print l,p

[1, 'insert', 2.5, 1.0, 1.5, 2.0] [4, 3]


In [50]:
l[2:5]

[2.5, 1.0, 1.5]

### 离题：控制结构

In [51]:
for element in l[2:5]:
    print element ** 2

6.25
1.0
2.25


In [52]:
r = range(0,8,1)
r

[0, 1, 2, 3, 4, 5, 6, 7]

In [53]:
type(r)

list

In [54]:
for i in range(2,5):
    print l[i] ** 2

6.25
1.0
2.25


In [55]:
for i in range(1,10):
    if i % 2 == 0:
        print "%d is even" % i
    elif i % 3 == 0:
        print "%d is multiple of 3" % i
    else:
        print "%d is odd" % i

1 is odd
2 is even
3 is multiple of 3
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is multiple of 3


In [56]:
total = 0
while total < 100:
    total += 1
print total

100


In [57]:
m = [i ** 2 for i in range(5)]
m

[0, 1, 4, 9, 16]

### 4.2.4 离题：函数式编程

In [58]:
def f(x):
    return x ** 2
f(2)

4

In [59]:
def even(x):
    return x % 2 == 0
even(3)

False

In [60]:
map(even,range(10))

[True, False, True, False, True, False, True, False, True, False]

In [61]:
map(lambda x: x**2,range(10))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [62]:
filter(even,range(15))

[0, 2, 4, 6, 8, 10, 12, 14]

In [63]:
reduce(lambda x,y :x+y,range(10))

45

In [64]:
def cumsum(l):
    total = 0
    for elem in l:
        total += elem
    return total
cumsum(range(10))

45

### 4.2.5 字典

In [65]:
d = {
    'Name':'Angela Merkel',
    'Country':'Germany',
    'Profession':'Chancelor',
    'Age': 60
}
type(d)

dict

In [66]:
print d['Name'],d['Age']

Angela Merkel 60


In [67]:
d.keys()

['Country', 'Age', 'Profession', 'Name']

In [68]:
d.values()

['Germany', 60, 'Chancelor', 'Angela Merkel']

In [69]:
d.items()

[('Country', 'Germany'),
 ('Age', 60),
 ('Profession', 'Chancelor'),
 ('Name', 'Angela Merkel')]

In [70]:
birthday = True
if birthday is True:
    d['Age'] += 1
print d['Age']

61


In [71]:
for item in d.iteritems():
    print item

('Country', 'Germany')
('Age', 61)
('Profession', 'Chancelor')
('Name', 'Angela Merkel')


In [72]:
for value in d.iteritems():
    print type(value)

<type 'tuple'>
<type 'tuple'>
<type 'tuple'>
<type 'tuple'>


### 4.2.6 集合

In [73]:
s = set(['u','d','ud','du','d','du'])
s

{'d', 'du', 'u', 'ud'}

In [75]:
t = set(["d",'dd','uu','u'])

In [76]:
s.union(t)

{'d', 'dd', 'du', 'u', 'ud', 'uu'}

In [77]:
s.intersection(t)

{'d', 'u'}

In [78]:
s.difference(t)

{'du', 'ud'}

In [79]:
s.symmetric_difference(t)#交集以外

{'dd', 'du', 'ud', 'uu'}

In [80]:
#集合对象的应用是去掉列表对象中的重复
from random import randint
l = [randint(0,10) for i in range(1000)]
len(l)

1000

In [81]:
l[:20]

[5, 3, 7, 6, 10, 2, 3, 8, 9, 7, 3, 2, 8, 5, 7, 5, 5, 5, 1, 10]

In [83]:
s = set(l)
s

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

## 4.3 NumPy数据结构

### 4.3.1 用Python列表形成数组

In [84]:
v = [0.5,0.75,1.0,1.5,2.0]

In [85]:
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [86]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [87]:
m[1][0]

0.5

In [88]:
v1 = [0.5,1.5]
v2 = [1,2]
m = [v1,v2]
c = [m,m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [89]:
c[1][1][0]

1

In [90]:
v = [0.5,0.75,1.0,1.5,2.0]
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [91]:
#此方式组合对象通常使用原始对象的引用指针
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [92]:
#使用copy模块的deepcopy函数可以避免这一现象
from copy import deepcopy
v = [0.5,0.75,1.0,1.5,2.0]
m = 3 * [deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [93]:
v[0] = 'Python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

### 4.3.2 常规NumPy数组

In [94]:
import numpy as np
a = np.array([0,0.5,1.0,1.5,2.0])
type(a)

numpy.ndarray

In [95]:
a[:2]

array([ 0. ,  0.5])

In [96]:
a.sum()

5.0

In [97]:
a.std()

0.70710678118654757

In [98]:
a.cumsum()

array([ 0. ,  0.5,  1.5,  3. ,  5. ])

In [99]:
a * 2

array([ 0.,  1.,  2.,  3.,  4.])

In [100]:
a ** 2

array([ 0.  ,  0.25,  1.  ,  2.25,  4.  ])

In [101]:
np.sqrt(a)

array([ 0.        ,  0.70710678,  1.        ,  1.22474487,  1.41421356])

In [102]:
b = np.array([a,a*2])
b

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 0. ,  1. ,  2. ,  3. ,  4. ]])

In [103]:
b[0]

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [104]:
b[0,2]

1.0

In [105]:
b.sum()

15.0

In [106]:
b.sum(axis = 0)

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [107]:
b.sum(axis = 1)

array([  5.,  10.])

In [108]:
c = np.zeros((2,3,4),dtype = 'i',order = 'C')
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [109]:
d = np.ones_like(c,dtype='float16',order='C')
d

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]], dtype=float16)

In [110]:
import random
I = 5000

In [111]:
%time mat = [[random.gauss(0,1) for j in range(I)] for i in range(I)]

Wall time: 20.3 s


In [112]:
%time reduce(lambda x,y:x+y,\
            [reduce(lambda x,y:x+y,row)\
            for row in mat])

Wall time: 3.4 s


3254.2563165227994

In [113]:
%time mat = np.random.standard_normal((I,I))

Wall time: 1.26 s


In [114]:
%time mat.sum()

Wall time: 56 ms


-6503.9772831054088

### 4.3.3 结构数组

In [116]:
dt = np.dtype([('Name','S10'),('Age','i4'),
              ('Height','f'),('Children/Pets','i4',2)])
s = np.array([('Smith',45,1.83,(0,1)),
             ('Jones',53,1.72,(2,2))],dtype=dt)
s

array([('Smith', 45,  1.83000004, [0, 1]),
       ('Jones', 53,  1.72000003, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [117]:
s['Name']

array(['Smith', 'Jones'],
      dtype='|S10')

In [118]:
s['Height'].mean()

1.7750001

In [119]:
s[1]['Age']

53

## 4.4 代码向量化
### 4.4.1 基本向量化

In [120]:
r = np.random.standard_normal((4,3))
s = np.random.standard_normal((4,3))

In [124]:
r + s

array([[ 1.17675144, -0.20616889, -1.44977398],
       [-2.32932175,  0.24892139, -0.05379621],
       [-1.58350107, -4.83953049, -0.40807032],
       [ 0.8191446 ,  0.07178232,  0.19527427]])

In [125]:
2 * r + 3

array([[ 2.82601482,  4.16041968,  1.27965649],
       [ 0.01871581,  3.66860909,  1.24469166],
       [ 1.70757045, -1.21012858,  1.83435629],
       [ 4.90457771,  2.63441286,  1.24640505]])

In [128]:
s = np.random.standard_normal(3)
r + s

array([[-0.37255604,  1.11395044,  1.27069602],
       [-1.77620555,  0.86804514,  1.25321361],
       [-0.93177822, -1.5713237 ,  1.54804592],
       [ 0.6667254 ,  0.35094702,  1.25407031]])

In [129]:
s = np.random.standard_normal(4)
r.transpose() + s

array([[ 0.13171516, -1.63621917, -0.53465534,  0.94428955],
       [ 0.79891759,  0.18872747, -1.99350486, -0.19079287],
       [-0.641464  , -1.02323125, -0.47126242, -0.88479678]])

In [132]:
np.shape(r.T)

(3L, 4L)

In [134]:
def f(x):
    return 3 * x + 5

In [135]:
f(0.5)

6.5

In [136]:
f(r)

array([[ 4.73902223,  6.74062952,  2.41948473],
       [ 0.52807371,  6.00291363,  2.36703749],
       [ 3.06135568, -1.31519287,  3.25153443],
       [ 7.85686656,  4.45161929,  2.36960757]])

In [137]:
import math
math.sin(r)#该函数用于处理浮点对象，即单个数值而非数组，NumPy提供了对应的函数，即所谓的通用函数（ufuncs）

TypeError: only length-1 arrays can be converted to Python scalars

In [138]:
np.sin(r)

array([[-0.08688291,  0.54819945, -0.75795461],
       [-0.99678937,  0.3281123 , -0.76924211],
       [-0.60216872, -0.86064162, -0.55038213],
       [ 0.81474476, -0.18177731, -0.76869444]])

In [139]:
np.sin(np.pi)#NumPy提供大量ufunc，将典型的数学函数推广到numpy.ndarray对象上

1.2246467991473532e-16

## 4.5 内存布局

In [140]:
x = np.random.standard_normal((5,10000000))
y = 2*x+3
C = np.array((x,y),order='C') # 类C语言内存布局
F = np.array((x,y),order='F') # 类Fortan内存布局
x = 0.0;y = 0.0#清除内存

In [143]:
C[:2].round(2)

array([[[ 0.17,  1.18, -0.11, ...,  1.34,  0.17, -0.97],
        [ 0.51, -0.44,  0.56, ..., -0.06, -0.92, -0.39],
        [-0.27, -0.15, -1.3 , ...,  1.24, -0.42, -0.08],
        [-0.53,  0.  ,  0.17, ...,  0.6 ,  0.65, -1.25],
        [-0.48,  0.94, -0.72, ...,  0.48,  1.11, -2.24]],

       [[ 3.34,  5.35,  2.78, ...,  5.68,  3.34,  1.06],
        [ 4.02,  2.13,  4.13, ...,  2.89,  1.16,  2.22],
        [ 2.46,  2.7 ,  0.4 , ...,  5.49,  2.16,  2.84],
        [ 1.95,  3.01,  3.34, ...,  4.21,  4.3 ,  0.5 ],
        [ 2.04,  4.89,  1.56, ...,  3.95,  5.21, -1.47]]])

In [144]:
%timeit C.sum()

10 loops, best of 3: 144 ms per loop


In [145]:
%timeit F.sum()

10 loops, best of 3: 147 ms per loop


In [146]:
%timeit C[0].sum(axis=0)

10 loops, best of 3: 127 ms per loop


In [147]:
%timeit C[0].sum(axis=1)

10 loops, best of 3: 71.8 ms per loop


In [150]:
%timeit F[0].sum(axis=0)

1 loop, best of 3: 214 ms per loop


In [151]:
%timeit F[0].sum(axis=1)

10 loops, best of 3: 157 ms per loop


In [152]:
F = 0.0;C = 0.0#清除内存

## 4.6 结语
从金融角度看，下面这些类型是最重要的：

*基本数据类型*

    在金融中，**整数、浮点数**和**字符串**提供了原子数据类型。

*标准数据类型*

    **元组、列表、字典**和**集合**类在金融中有许多应用领域，**列表**通常是最灵活的主力。

*数组*

    金融相关问题和算法中的一大类可以转换为数组；NumPy提供了专门的**numpy.ndarray**类，该类提供了代码方便性、简洁性和高性能。
## 4.7 延伸阅读